"""
hallucination_checker_tool.py
────────────────────────────────────────────────
Two-stage hallucination detection:

  Stage 1 (heuristic, fast):
    1. Split generated answer into sentences.
    2. For each sentence, check if any content word appears in
       the retrieved context (substring overlap).
    3. Flag sentences with zero context support.

  Stage 2 (LLM judge, accurate):
    4. Only runs if Stage 1 flagged sentences.
    5. Calls litellm with a judge prompt for nuanced evaluation.
    6. Returns specific unsupported claims with explanations.
"""

from __future__ import annotations

import json
import logging
import os
import re
from typing import Any

from crewai.tools import BaseTool
from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)

# A sentence is "supported" if at least this many content words
# (len > 3) from it appear in the retrieved context.
MIN_SUPPORT_WORDS = 2


# Description: Strips irrelevant characters specifically to maximize the substring matching used for hallucination checks.
def _clean(text: str) -> str:
    """Remove diacritics and punctuation for matching."""
    text = re.sub(r"[\u0610-\u061A\u064B-\u065F\u0670]", "", text)
    text = re.sub(r"[^\u0600-\u06FF\u0750-\u077F\s\w]", " ", text)
    return text.lower()


# Description: Intelligently cuts a cohesive Arabic paragraph into sentences based on terminating punctuation logic.
def _split_sentences(text:str) -> list[str]:
    """Split on Arabic/Latin sentence terminators."""
    sentences = re.split(r"[.!?؟،\n]+", text)
    return [s.strip() for s in sentences if len(s.strip()) > 10]


# Description: Specifies the expected input payload schema from the AI agent.
class HallucinationCheckerInput(BaseModel):
    generated_answer: str = Field(
        ..., description="The Arabic answer generated by the medical response agent."
    )
    retrieved_context: str = Field(
        ..., description="The raw context text from citation_grounding_tool ('context' field)."
    )


# Description: A blazing fast text-verification tool! It compares the generated answer directly against the retrieved sources to mathematically detect fabricated lines.
class HallucinationCheckerTool(BaseTool):
    name: str        = "hallucination_checker_tool"
    description: str = (
        "Perform lightweight hallucination detection on the generated Arabic answer. "
        "Checks each sentence against retrieved context. "
        "Returns JSON with hallucination_detected flag and any flagged claims."
    )
    args_schema: type[BaseModel] = HallucinationCheckerInput

    # Description: Sentences from the answer are iterated here. Any sentence containing ZERO overlaps with the source chunks is aggressively flagged!
    def _run(self, generated_answer: str, retrieved_context: str) -> str:
        context_clean = _clean(retrieved_context)
        context_words = set(w for w in context_clean.split() if len(w) > 3)

        sentences      = _split_sentences(generated_answer)
        flagged        = []
        unsupported    = []

        for sent in sentences:
            # Skip the disclaimer sentence
            if "تعليمية" in sent or "استشارة" in sent or "طبيب" in sent:
                continue

            sent_clean = _clean(sent)
            sent_words = [w for w in sent_clean.split() if len(w) > 3]

            if not sent_words:
                continue

            # Count how many sentence words appear in the context
            support_count = sum(1 for w in sent_words if w in context_words)

            coverage = support_count / len(sent_words) if sent_words else 1.0

            if coverage < 0.15 and len(sent_words) >= 5:
                flagged.append(sent)

        if flagged:
            result: dict[str, Any] = {
                "hallucination_detected": True,
                "flagged_count":          len(flagged),
                "unsupported_claims":     flagged[:3],   # show at most 3
                "recommendation": (
                    "يُنصح بمراجعة الادعاءات المُعلَّمة مقارنةً بالمصادر المسترجعة."
                ),
            }
            logger.warning(f"Hallucination check flagged {len(flagged)} sentence(s).")
        else:
            result = {
                "hallucination_detected": False,
                "flagged_count":          0,
            }
            logger.info("Hallucination check passed – no unsupported claims detected.")

        return json.dumps(result, ensure_ascii=False, indent=2)

    @staticmethod
    def _run_llm_judge(
        answer: str,
        context: str,
        flagged_sentences: list[str],
        model: str,
        api_key: str,
        api_base: str | None = None,
    ) -> str:
        """
        Stage 2: LLM-based hallucination judge.

        Evaluates each flagged sentence against the retrieved context
        using an LLM call. Returns JSON with specific unsupported claims.
        """
        import litellm

        sentences_text = "\n".join(f"- {s}" for s in flagged_sentences)

        judge_prompt = f"""أنت مدقق حقائق طبي. مهمتك تقييم ما إذا كانت الجمل التالية من إجابة الطبيب مدعومة بالمصادر الطبية المسترجعة أم لا.

## المصادر الطبية المسترجعة:
{context}

## الإجابة الكاملة للطبيب:
{answer}

## الجمل المشتبه فيها:
{sentences_text}

## التعليمات:
- لكل جملة، قرر: "مدعومة" (المعلومة موجودة في المصادر أو مفهومة ضمناً) أو "غير مدعومة" (المعلومة غير موجودة في المصادر أو تتعارض معها).
- إذا كانت الجملة تعميمًا صحيحًا بناءً على المعلومات الموجودة، اعتبرها مدعومة.
- كن دقيقًا ولا تتعسف في التقييم.

أجب بصيغة JSON فقط دون أي نص إضافي:
{{
  "verdicts": [
    {{
      "sentence": "...",
      "supported": true,
      "explanation": "..."
    }}
  ]
}}"""

        kwargs = {"model": model, "api_key": api_key}
        if api_base:
            kwargs["api_base"] = api_base

        try:
            resp = litellm.completion(
                messages=[{"role": "user", "content": judge_prompt}],
                max_tokens=800,
                temperature=0.0,
                **kwargs,
            )
            content = resp.choices[0].message.content or ""

            # Extract JSON from response (handle markdown-wrapped JSON)
            content = content.strip()
            if "```json" in content:
                content = content.split("```json")[1].split("```")[0].strip()
            elif "```" in content:
                content = content.split("```")[1].split("```")[0].strip()

            verdicts = json.loads(content)
            unsupported = [
                v for v in verdicts.get("verdicts", []) if not v.get("supported", True)
            ]

            result: dict[str, Any] = {
                "hallucination_detected": len(unsupported) > 0,
                "flagged_count": len(unsupported),
                "unsupported_claims": [
                    {
                        "sentence": v["sentence"],
                        "explanation": v.get("explanation", ""),
                    }
                    for v in unsupported[:3]
                ],
                "recommendation": (
                    "الادعاءات التالية قد لا تكون مدعومة بالمصادر المسترجعة."
                    if unsupported
                    else "جميع الادعاءات مدعومة بالمصادر."
                ),
            }
        except Exception as e:
            logger.error(f"LLM judge failed: {e}")
            result = {
                "hallucination_detected": True,
                "flagged_count": len(flagged_sentences),
                "unsupported_claims": [
                    {"sentence": s, "explanation": "تعذر تدقيق هذه المعلومة بواسطة المدقق."}
                    for s in flagged_sentences[:3]
                ],
                "recommendation": "حدث خطأ أثناء التدقيق. يُنصح بمراجعة الادعاءات يدوياً.",
            }

        logger.info(
            f"LLM judge verdict: {result['flagged_count']} unsupported claim(s)."
        )
        return json.dumps(result, ensure_ascii=False, indent=2)
