"""
hallucination_checker_tool.py
────────────────────────────────────────────────
Lightweight hallucination detection.

Strategy (no LLM re-call → fast inference):
  1. Split generated answer into sentences.
  2. For each sentence, check if any content word appears in
     the retrieved context (substring overlap).
  3. Flag sentences with zero context support.
  4. Return lightweight JSON verdict.
"""

from __future__ import annotations

import json
import logging
import re
from typing import Any

from crewai.tools import BaseTool
from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)

# A sentence is "supported" if at least this many content words
# (len > 3) from it appear in the retrieved context.
MIN_SUPPORT_WORDS = 2


# Description: Strips irrelevant characters specifically to maximize the substring matching used for hallucination checks.
def _clean(text: str) -> str:
    """Remove diacritics and punctuation for matching."""
    text = re.sub(r"[\u0610-\u061A\u064B-\u065F\u0670]", "", text)
    text = re.sub(r"[^\u0600-\u06FF\u0750-\u077F\s\w]", " ", text)
    return text.lower()


# Description: Intelligently cuts a cohesive Arabic paragraph into sentences based on terminating punctuation logic.
def _split_sentences(text:str) -> list[str]:
    """Split on Arabic/Latin sentence terminators."""
    sentences = re.split(r"[.!?؟،\n]+", text)
    return [s.strip() for s in sentences if len(s.strip()) > 10]


# Description: Specifies the expected input payload schema from the AI agent.
class HallucinationCheckerInput(BaseModel):
    generated_answer: str = Field(
        ..., description="The Arabic answer generated by the medical response agent."
    )
    retrieved_context: str = Field(
        ..., description="The raw context text from citation_grounding_tool ('context' field)."
    )


# Description: A blazing fast text-verification tool! It compares the generated answer directly against the retrieved sources to mathematically detect fabricated lines.
class HallucinationCheckerTool(BaseTool):
    name: str        = "hallucination_checker_tool"
    description: str = (
        "Perform lightweight hallucination detection on the generated Arabic answer. "
        "Checks each sentence against retrieved context. "
        "Returns JSON with hallucination_detected flag and any flagged claims."
    )
    args_schema: type[BaseModel] = HallucinationCheckerInput

    # Description: Sentences from the answer are iterated here. Any sentence containing ZERO overlaps with the source chunks is aggressively flagged!
    def _run(self, generated_answer: str, retrieved_context: str) -> str:
        context_clean = _clean(retrieved_context)
        context_words = set(w for w in context_clean.split() if len(w) > 3)

        sentences      = _split_sentences(generated_answer)
        flagged        = []
        unsupported    = []

        for sent in sentences:
            # Skip the disclaimer sentence
            if "تعليمية" in sent or "استشارة" in sent or "طبيب" in sent:
                continue

            sent_clean = _clean(sent)
            sent_words = [w for w in sent_clean.split() if len(w) > 3]

            if not sent_words:
                continue

            # Count how many sentence words appear in the context
            support_count = sum(1 for w in sent_words if w in context_words)

            coverage = support_count / len(sent_words) if sent_words else 1.0

            if coverage < 0.15 and len(sent_words) >= 5:
                flagged.append(sent)

        if flagged:
            result: dict[str, Any] = {
                "hallucination_detected": True,
                "flagged_count":          len(flagged),
                "unsupported_claims":     flagged[:3],   # show at most 3
                "recommendation": (
                    "يُنصح بمراجعة الادعاءات المُعلَّمة مقارنةً بالمصادر المسترجعة."
                ),
            }
            logger.warning(f"Hallucination check flagged {len(flagged)} sentence(s).")
        else:
            result = {
                "hallucination_detected": False,
                "flagged_count":          0,
            }
            logger.info("Hallucination check passed – no unsupported claims detected.")

        return json.dumps(result, ensure_ascii=False, indent=2)
